- hosts: 127.0.0.1
  remote_user: root
  connection: local
  vars_files:
    - ./group_vars/masters
  tasks:
  - name: Copy kubernetes yum.repo for contral panle
    copy: src=./roles/common/files/kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo
  - name: Install kubectl for contral panle
    yum: name="kubectl-{{ kube_version }}" state=present
