- hosts: masters
  remote_user: root
  gather_facts: no
  vars:
    master02_ip: "{{ groups['master02'][0] }}"
    master03_ip: "{{ groups['master03'][0] }}"
  tasks:
    # - shell: rpm -q docker-ce
    #   register: docker_info
    #   ignore_errors: true
    - name: test 1
      debug:
        msg: "{{ role_dir }}"
      # when: (docker_info is failed) or (docker_version not in docker_info['stdout'])
      # with_items:
      #   - "{{ groups['master01'] }}"
    # - name: test 2
    #   debug:
    #     msg: "test:----{{ hostvars[master02_ip]['host_name'] }}"
    # - name: test
    #   command: systemctl status kubelet
    #   ignore_errors: true
    #   changed_when: false
    #   register: result
    #
    # - name: test1
    #   debug:
    #     msg: "{{ result }}"
