- hosts: etcds
  remote_user: doors
  gather_facts: no
  connection: local
  vars:
  tasks:
    - debug:
        msg: "{{ ansible_all_ipv4_addresses }}"
      # when: host_name
      # when: (docker_info is failed) or (docker_version not in docker_info['stdout'])
      # with_items:
      #   - "{{ groups['master01'] }}"
    # - name: test 2
    #   debug:
    #     msg: "test:----{{ hostvars[master02_ip]['host_name'] }}"
    # - name: test
    #   command: systemctl status kubelet
    #   ignore_errors: true
    #   changed_when: false
    #   register: result
    #
    # - name: test1
    #   debug:
    #     msg: "{{ result }}"
