defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    # [entryPoints.http.redirect]
    #   entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.dockerhub]
  address = ":5000"
    [entryPoints.dockerhub.tls]
      [[entryPoints.dockerhub.tls.certificates]]
      CertFile = "/dockerhub-certs/tls.crt"
      KeyFile = "/dockerhub-certs/tls.key"
