apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logrotate
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: logrotate
  template:
    metadata:
      labels:
        k8s-app: logrotate
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: logrotate
        image:  blacklabelops/logrotate:1.3
        env:
        - name: LOGS_DIRECTORIES
          value: "/var/log/docker /var/lib/docker/containers"
        - name: LOGROTATE_INTERVAL
          value: "daily"
        - name: LOGROTATE_SIZE
          value: "500M"
        - name: LOGROTATE_COMPRESSION
          value: "compress"
        - name: LOGROTATE_OLDDIR
          value: "/logs"
        - name: LOGROTATE_AUTOUPDATE
          value: "false"
        - name: LOGROTATE_CRONSCHEDULE
          value: "0 0 * * * *"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: containers
          mountPath: /var/lib/docker/containers
        - name: oldlogs
          mountPath: /logs
      volumes:
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: oldlogs
        hostPath:
          path: /var/log/containers/
