- name: mkdir for master other
  file: path=/etc/kubernetes/pki/etcd state=directory

- name: Copy ca files to master other
  copy: src=../files/{{ item }} dest=/etc/kubernetes/pki/{{ item }}
  with_items:
    - "apiserver-etcd-client.crt"
    - "apiserver-etcd-client.key"
    - "etcd/ca.crt"
    - "sa.key"
    - "sa.pub"
    - "ca.crt"
    - "ca.key"
    - "front-proxy-ca.crt"
    - "front-proxy-ca.key"
    - "apiserver.crt"
    - "apiserver.key"
    - "apiserver-kubelet-client.crt"
    - "apiserver-kubelet-client.key"
    - "front-proxy-client.crt"
    - "front-proxy-client.key"

- name: Copy kubeadm config file to master other
  template: src=../templates/kubeadm-config.yaml dest=/root/kubeadm-config.yaml owner=root group=root mode=0644

- name: Check the kubelet status master other
  command: systemctl status kubelet
  ignore_errors: true
  changed_when: false
  register: kubelet_status

- name: Install kubernets master other with kubeadm
  shell: kubeadm init --config /root/kubeadm-config.yaml
  when: kubelet_status is failed
