- name: mkdir for master02
  file: path=/etc/kubernetes/pki/ state=directory

- name: Copy ca files to master02
  copy: src=../files/{{ item }} dest=/etc/kubernetes/pki/{{ item }}
  with_items:
    - "ca.crt"
    - "ca.key"
    - "sa.key"
    - "sa.pub"
    - "front-proxy-ca.crt"
    - "front-proxy-ca.key"
# - name: Copy etcd ca files to master02
#   copy: src=etcd/{{ item }} dest=/etc/kubernetes/pki/etcd/{{ item }}
#   with_items:
#     - "ca.crt"
#     - "ca.key"
- name: Copy admin.conf to master02
  copy: src=../files/admin.conf dest=/etc/kubernetes/admin.conf

- name: Copy kubeadm config file to master02
  template: src=../templates/kubeadm-config.yaml dest=/root/kubeadm-config.yaml owner=root group=root mode=0644

- name: Add kubectl environment variable
  shell: "echo KUBECONFIG=/etc/kubernetes/admin.conf >> /etc/bashrc"

# Phase certs and install etcd02
- name: Phase certs call on master02
  shell: kubeadm alpha phase certs all --config /root/kubeadm-config.yaml
- name: Phase kubelet config on master02
  shell: kubeadm alpha phase kubelet config write-to-disk --config /root/kubeadm-config.yaml
- name: phase kubelet write-env-file on master02
  shell: kubeadm alpha phase kubelet write-env-file --config /root/kubeadm-config.yaml
- name: alpha phase kubeconfig kubelet on master02
  shell: kubeadm alpha phase kubeconfig kubelet --config /root/kubeadm-config.yaml

- name: Start kubelet on master02
  systemd: name=kubelet state=started

- name: Wait the load_blance_ip:port is available
  shell: "echo '' | telnet {{ load_blance_ip }} {{ load_blance_port }}"
  ignore_errors: true
- name: Add etcd master02
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl exec -n kube-system etcd-{{ hostvars[master01_ip]['host_name'] }} -- etcdctl --ca-file /etc/kubernetes/pki/etcd/ca.crt --cert-file /etc/kubernetes/pki/etcd/peer.crt --key-file /etc/kubernetes/pki/etcd/peer.key --endpoints=https://{{ master01_ip }}:2379 member add {{ hostvars[master02_ip]['host_name'] }} https://{{ master02_ip }}:2380"

- name: phase etcd local on master02
  shell: kubeadm alpha phase etcd local --config /root/kubeadm-config.yaml

# Deploy the control plane components and mark the node as a master
- name: phase kubeconfig all on master02
  shell: kubeadm alpha phase kubeconfig all --config /root/kubeadm-config.yaml

- name: phase controlplane all on master02
  shell: kubeadm alpha phase controlplane all --config /root/kubeadm-config.yaml

- name: phase mark-master on master02
  shell: kubeadm alpha phase mark-master --config /root/kubeadm-config.yaml
  async: 600
  poll: 0
