- name: Check the kubelet status master other
  command: systemctl status kubelet
  ignore_errors: true
  changed_when: false
  register: kubelet_status

- name: If kubelet is running, terminate tasks
  fail:
    msg: Kubelet if running, terminate tasks
  when: kubelet_status is success

- name: mkdir for master other
  file: path=/etc/kubernetes/pki/etcd state=directory

- name: Copy ca files to master other
  copy: src="{{ item }}" dest="/etc/kubernetes/pki/{{ item }}"
  with_items:
    - "apiserver-etcd-client.crt"
    - "apiserver-etcd-client.key"
    - "etcd/ca.crt"
    - "sa.key"
    - "sa.pub"
    - "ca.crt"
    - "ca.key"
    - "front-proxy-ca.crt"
    - "front-proxy-ca.key"
    - "apiserver.crt"
    - "apiserver.key"
    - "apiserver-kubelet-client.crt"
    - "apiserver-kubelet-client.key"
    - "front-proxy-client.crt"
    - "front-proxy-client.key"

- name: Copy kubeadm config file to master other
  template: src=kubeadm-config.yaml dest=/root/kubeadm-config.yaml owner=root group=root mode=0644

- name: Install kubernets master other with kubeadm
  shell: kubeadm init --config /root/kubeadm-config.yaml
  register: kubeadm_response

- name: terminate tasks if kubeadm excute failed
  fail:
    msg: kubeadm execute failed
  when: kubeadm_response is failed
