{
 "title": "K8s Container",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "grafana-kubernetes-datasource" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": "node" },
   { "name": "namespace", "query": "namespace" },
   { "name": "pod", "label": "Pod", "query": "pod $namespace" }
  ]
 },
 "panels": [
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage of containers across a cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"$pod\",namespace=~\"$namespace\",instance=~\"$node\", image!=\"\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod_name=~\"$pod\",namespace=~\"$namespace\",instance=~\"$node\",image!=\"\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_transmit_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\",namespace=~\"$namespace\",instance=~\"$node\",image!=\"\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{pod_name=~\"$pod\", kubernetes_io_hostname=~\"$node\",namespace=~\"$namespace\",instance=~\"$node\",image!=\"\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "network traffic packets inbound",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (irate(container_network_receive_packets_total{pod_name=~\"$pod\",instance=~\"$node\",namespace=~\"$namespace\",image!=\"\"}[1m]))",
     "legendFormat": "{{ pod_name }}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "network traffic packets outbound",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (irate(container_network_transmit_packets_total{pod_name=~\"$pod\", namespace=~\"$namespace\", instance=~\"$node\",image!=\"\"}[1m]))",
     "legendFormat": "{{ pod_name }}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_fs_io_time_seconds_total{pod_name=~\"$pod\",instance=~\"$node\",namespace=~\"$namespace\",image!=\"\"}[2m])) by (pod_name)",
     "legendFormat": "{{pod_name}}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_fs_write_seconds_total{pod_name=~\"$pod\",namespace=~\"$namespace\",instance=~\"$node\",image!=\"\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Bob Marley", "type": "text", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 } }
 ]
}