{
 "title": "K8s Node",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "grafana-kubernetes-datasource" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "label": "node:", "query": "node" }
  ]
 },
 "panels": [
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu{instance=~\"$node\", mode=\"system\"}[1m]))",
     "legendFormat": "system"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$node\", mode=\"user\"}[1m]))",
     "legendFormat": "user"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$node\", mode=~\"iowait\"}[1m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(irate(node_cpu{instance=~\"$node\", mode=~\"steal\"}[1m]))",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "node cpu load 1 min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "load_1_mins",
     "type": "timeserie"
    },
    {
     "expr": "machine_cpu_cores{instance=~\"$node\"}",
     "legendFormat": "cores"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable{instance=~\"$node\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(node_memory_MemFree{instance=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_memory_Active{instance=~\"$node\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Disk Usage and Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free{instance=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_filesystem_size{instance=~\"$node\",mountpoint=\"/\"}) - sum(node_filesystem_free{instance=~\"$node\",mountpoint=\"/\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read{instance=~\"$node\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written{instance=~\"$node\"}[5m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed{instance=~\"$node\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed{instance=~\"$node\"}[5m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"$node\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes{instance=~\"$node\"}[5m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(node_network_receive_errs{instance=~\"$node\"})",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(node_network_transmit_errs{instance=~\"$node\"})",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets{instance=~\"$node\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_packets{instance=~\"$node\"}[5m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  { "title": "Pink Floyd", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 } }
 ]
}