- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../../../group_vars/masters
  tasks:
  - name: Check the loadblance port 6443
    wait_for:
      host: "{{ load_blance_ip }}"
      port: 6443
      delay: 5
      state: started
      timeout: 60
  - name: install extends
    shell:  cd ./../scripts && sh install.sh
