- name: Check the loadblance port 6443
  wait_for:
    host: "{{ load_blance_ip }}"
    port: 6443
    delay: 5
    state: started
    timeout: 60
- name: install extends
  shell: "sh {{ playbook_dir }}/roles/extensions/scripts/install.sh"
