- name: generate config files from templates
  template: src=../templates/{{ item }} dest=../files/{{ item }}
  with_items:
  - "etcd_master01.conf"
  - "etcd_master02.conf"
  - "etcd_master03.conf"
  - "peer.json"
  - "server.json"

- name: generate etcd certs
  shell: cd ../scripts/ && ./gencerts.sh
