- name: Check etcd status
  command: systemctl status etcd
  register: etcd_response
  ignore_errors: true

- name: terminate tasks if etcd is running
  fail:
    msg: etcd is running, terminated tasks.
  when: etcd_response is success

# - name: Remove old etcd
#   yum: name=etcd* state=absent

# - name: Remove old etcd datas
#   command: rm -rf /var/lib/etcd/default.etcd/*

- name: Install etcd
  yum: name="etcd-{{ etcd_version }}" state=present

- name: Make dir to restore etcd certs
  file: path=/etc/ssl/etcd state=directory

- name: Copy file to etcd hosts
  copy: src="{{ item }}" dest=/etc/ssl/etcd/ owner=root group=root mode=0600
  with_fileglob:
    - ../files/*.pem

- name: Copy etcd01 config to hosts
  template: src=etcd_master01.conf dest=/etc/etcd/etcd.conf
  when: host_name == "etcd01"
- name: Copy etcd02 config to hosts
  template: src=etcd_master02.conf dest=/etc/etcd/etcd.conf
  when: host_name == "etcd02"
- name: Copy etcd03 config to hosts
  template: src=etcd_master03.conf dest=/etc/etcd/etcd.conf
  when: host_name == "etcd03"

- name: Copy etcd service config to hosts
  copy: src=etcd.service dest=/usr/lib/systemd/system/etcd.service

- name: systemd daemon_reload
  systemd: daemon_reload=yes


- name: start etcd01
  systemd: name=etcd state=started enabled=yes
  async: 300
  poll: 0
  when: host_name == "etcd01"

- name: wait 3s for etcd01 start
  wait_for: timeout=1

- name: start etcd2
  systemd: name=etcd state=started enabled=yes
  async: 300
  poll: 0
  when: host_name == "etcd02"

- name: start etcd3
  systemd: name=etcd state=started enabled=yes
  async: 300
  poll: 0
  when: host_name == "etcd03"
