apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: "v{{ kube_version }}"
apiServerCertSANs:
- "{{ load_blance_ip }}"
- "{{ master01_ip }}"
- "{{ master02_ip }}"
- "{{ master03_ip }}"
controlPlaneEndpoint: "{{ load_blance_ip }}:{{ load_blance_port }}"
etcd:
  external:
    endpoints:
    - "https://{{ etcd01_ip }}:2379"
    - "https://{{ etcd02_ip }}:2379"
    - "https://{{ etcd03_ip }}:2379"
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  # This CIDR is a Calico default. Substitute or remove for your CNI provider.
  serviceSubnet: "10.96.0.0/12"
  dnsDomain: "cluster.local"
  podSubnet: "10.244.0.0/16"
kubeProxy:
  config:
    featureGates:
      SupportIPVSProxyMode: true
    mode: ipvs
