apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.0
apiServerCertSANs:
- "{{ load_blance_ip }}"
- "{{ master01_ip }}"
- "{{ master02_ip }}"
- "{{ master03_ip }}"
api:
    controlPlaneEndpoint: "{{ load_blance_ip }}:{{ load_blance_port }}"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://{{ master02_ip }}:2379"
      advertise-client-urls: "https://{{ master02_ip }}:2379"
      listen-peer-urls: "https://{{ master02_ip }}:2380"
      initial-advertise-peer-urls: "https://{{ master02_ip }}:2380"
      initial-cluster: "{{ hostvars[master01_ip]['host_name'] }}=https://{{ master01_ip }}:2380, {{ hostvars[master02_ip]['host_name'] }}=https://{{ master02_ip }}:2380"
      initial-cluster-state: existing
    serverCertSANs:
      - {{ hostvars[master02_ip]['host_name'] }}
      - {{ master02_ip }}
    peerCertSANs:
      - {{ hostvars[master02_ip]['host_name'] }}
      - {{ master02_ip }}
networking:
    # This CIDR is a Calico default. Substitute or remove for your CNI provider.
    podSubnet: "192.168.0.0/16"
