---
- name: Check if docker installed and version right
  shell: rpm -q docker
  args:
    warn: false
  register: docker_response
  ignore_errors: true

- name: Create the repository for docker
  copy: src=docker-ce.repo dest=/etc/yum.repos.d/docker-ce.repo

- name: remove old docker
  yum: name=docker* state=absent
  when: (docker_response is failed) or (docker_version not in docker_response['stdout'])

- name: Clean docker old datas
  shell: rm -rf /var/lib/docker/*
  args:
    warn: false
  when: (docker_response is failed) or (docker_version not in docker_response['stdout'])

- name: install docker
  yum: name="docker-{{ docker_version }}" state=present
  when: (docker_response is failed) or (docker_version not in docker_response['stdout'])

- name: change docker group driver to cgroupfs
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    regexp: 'native.cgroupdriver=systemd'
    line: 'native.cgroupdriver=cgroupfs'

- name: Start docker
  systemd: name=docker state=started enabled=yes
