# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewer-bind
subjects:
- kind: ServiceAccount
  name: viewer
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
