groups:
  - name: ptonlineRules
    interval: 15s
    rules:
      - record: node_ptonline:node_memory_free:memory_available_percents
        expr: node_memory_MemAvailable{job="node_ptonline"} / on(instance) node_memory_MemTotal{job="node_ptonline"}

      - record: node_ptonline:node_filesystem_free:node_filesystem_free_percents
        expr: node_filesystem_free{job="node_ptonline",mountpoint="/"} / on(instance) node_filesystem_size{job="node_ptonline",mountpoint="/"}

      - record: node_ptonline:node_cpu:node_cpu_usage_percents
        expr: 1 - avg(irate(node_cpu{job='node_ptonline',mode='idle'}[1m])) by (instance)


  - name: ptonlineAlertingNode
    interval: 15s
    rules:
      - alert: InstanceDown
        expr: up{job='node_ptonline'} == 0
        for: 1m
        labels:
          severity: Critical
          group: ptonline_node
        annotations:
          summary: "Instance {{ $labels.instance }} - shut down"

      - alert: CpuLoadHigh
        expr: node_load1{job='node_ptonline'} / on(instance) machine_cpu_cores * 100 > 80
        for: 1m
        labels:
          severity: High
          group: ptonline_node
        annotations:
          summary: "Cpu load over {{ $value }}"

      - alert: CpuUsageHigh
        expr:  node_ptonline:node_cpu:node_cpu_usage_percents * 100 > 80
        for: 1m
        labels:
          severity: High
          group: ptonline_node
        annotations:
          summary: "Cpu Usage Over {{ $value }}%"

      - alert: Memory20%Available2
        expr: node_ptonline:node_memory_free:memory_available_percents * 100 <= 20
        for: 1m
        labels:
          severity: High
          group: ptonline_node
        annotations:
          summary: "{{ $value }}% memory Available"

      - alert: DiskSpace15%Free
        expr: node_ptonline:node_filesystem_free:node_filesystem_free_percents * 100 <= 15
        labels:
          severity: High
          group: ptonline_node
        annotations:
          summary: "{{ $value }}%  disk free"
